[[headers]]
  for = "/Build/*.data.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/Build/*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"

[[headers]]
  for = "/Build/*.js"
  [headers.values]
    Content-Encoding = "js"
    Content-Type = "application/javascript"

[[headers]]
  for = "/Build/*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-Xss-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Access-Control-Allow-Origin = "*.peanutgames.com, *.peanuthub.dev, *.netlify.app"
    Accept-Encoding = "gzip, compress, br"
    Content-Security-Policy = "frame-ancestors https://peanutgames.com https://peanuthub.dev https://*.netlify.app http://localhost"
    Cache-Control = '''
          max-age=0,
          no-cache,
          no-store,
          must-revalidate'''          

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
