name: Upload to AWS S3

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Uploading to S3 development
        if: github.base_ref == 'development'
        run: |
          find ./Build -type f -exec aws s3 cp {} s3://peanutgames/rock-dev/{} --cache-control 'max-age=31536000' --content-encoding 'br' \;

      - name: Uploading to S3 Production
        if: github.base_ref == 'main'
        run: |
          find ./Build -type f -exec aws s3 cp {} s3://peanutgames/rock-prod/{} --cache-control 'max-age=31536000' --content-encoding 'br' \;
