name: Upload to AWS S3

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - development
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Uploading to S3 Development
        if: github.base_ref == 'development'
        run: |
          find ./Build -type f -exec bash -c '
            file="$1"
            ext="${file##*.}"
            if [[ "$ext" == "br" ]]; then
              encoding="--content-encoding br"
            else
              encoding=""
            fi
            aws s3 cp "$file" "s3://peanutgames/rock-dev/${file##*/}" --cache-control "max-age=31536000" $encoding
          ' _ {} \;

      - name: Uploading to S3 Production
        if: github.base_ref == 'main'
        run: |
          find ./Build -type f -exec bash -c '
            file="$1"
            ext="${file##*.}"
            if [[ "$ext" == "br" ]]; then
              encoding="--content-encoding br"
            else
              encoding=""
            fi
            aws s3 cp "$file" "s3://peanutgames/rock-prod/${file##*/}" --cache-control "max-age=31536000" $encoding
          ' _ {} \;
